# Generated by Django 4.1.5 on 2023-01-20 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
    ]
