# Generated by Django 4.1.5 on 2023-01-20 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20230120_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='videolesson',
            name='video',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='video.video'),
        ),
    ]
